const fs=require('fs');
function expect(v,m){if(!v)throw new Error(m);}
const local=fs.readFileSync('public/app-bgm-local.js','utf8');
const index=fs.readFileSync('public/index.html','utf8');
new Function(local);
expect(index.includes('"app-brand-bgm.js","app-bgm-local.js","app-16.js"'),'same-origin BGM override must load after brand audio and before App');
expect(local.includes('const SRC="/assets/maou_bgm_cyber44.mp3?v="'),'Cyber44 must be served from same origin');
expect(local.includes('4dedd2b97b80aca8ab47e9b797ad0e8a400c1e941a43b1c2b53aca40ea9cc532'),'Cyber44 source hash marker missing');
expect(local.includes('const BGM_OUTPUT_SCALE=0.10'),'BGM output must be reduced to 10 percent of the original level');
expect(local.includes('this.volume*BGM_OUTPUT_SCALE'),'BGM scale must apply to effective playback volume');
expect(local.includes('window.__sixBallGameplayBgmOutputScale=BGM_OUTPUT_SCALE'),'BGM output-scale diagnostic marker missing');
expect(local.includes('window.__sixBallGameplayBgmSameOrigin=true'),'same-origin marker missing');
expect(local.includes('legacy.prime=function()')&&local.includes('legacy.start=function()'),'legacy cross-origin BGM must be disabled');
expect(local.includes('Bgm.prime();'),'BGM must be primed under menu user gesture');
expect(local.includes('Bgm.start(true);'),'BGM must start when GAME becomes visible');
expect(local.includes('document.addEventListener("click",()=>sync(),{capture:false})'),'Safari BGM promotion must remain in the same click without setTimeout');
expect(!local.includes('setTimeout(sync,0)'),'BGM start must not be deferred out of the trusted click');
expect(local.includes('resumeGameSfxContext()'),'gameplay SFX AudioContext recovery missing');
expect(local.includes('Sfx.__sixBallSafariResumeBridge=true'),'SFX resume bridge marker missing');
expect(local.includes('ctx.state==="suspended"'),'suspended WebAudio context recovery missing');
expect(local.includes('ctx.resume()'),'WebAudio resume call missing');
expect(local.includes('window.__sixBallSfxSafariResumeBridge=true'),'SFX recovery diagnostic marker missing');
expect(local.includes('a.loop=true'),'BGM must loop');
expect(!local.includes('stepEngine(')&&!local.includes('settlePass(')&&!local.includes('SLIDE_SPEED')&&!local.includes('GRAV='),'local audio adapter must not alter gameplay physics');
console.log('same-origin Cyber44 + Safari gameplay SFX + 10pct BGM regression PASS');
