const fs=require('fs');
function expect(v,m){if(!v)throw new Error(m);}
const local=fs.readFileSync('public/app-bgm-local.js','utf8');
const index=fs.readFileSync('public/index.html','utf8');
new Function(local);
expect(index.includes('"app-brand-bgm.js","app-bgm-local.js","app-16.js"'),'same-origin BGM override must load after brand audio and before App');
expect(/const SRC="\/assets\/[^"?]+\.mp3\?v="\+HASH\.slice\(0,16\)/.test(local),'gameplay BGM must be served from a same-origin MP3 asset');
expect(/const HASH="[0-9a-f]{64}"/.test(local),'gameplay BGM source hash marker missing');
expect(/const BGM_OUTPUT_SCALE=0\.\d+/.test(local),'BGM output scale missing');
expect(local.includes('this.volume*BGM_OUTPUT_SCALE'),'BGM scale must apply to effective playback volume');
expect(local.includes('window.__sixBallGameplayBgmOutputScale=BGM_OUTPUT_SCALE'),'BGM output-scale diagnostic marker missing');
expect(local.includes('window.__sixBallGameplayBgmSameOrigin=true'),'same-origin marker missing');
expect(local.includes('legacy.prime=function()')&&local.includes('legacy.start=function()'),'legacy cross-origin BGM must be disabled');
expect(local.includes('Bgm.prime();'),'BGM must be primed under menu user gesture');
expect(local.includes('Bgm.start(true);'),'BGM must start when GAME becomes visible');
expect(local.includes('document.addEventListener("click",()=>sync(),{capture:false})'),'Safari BGM promotion must remain in the same click without setTimeout');
expect(!local.includes('setTimeout(sync,0)'),'BGM start must not be deferred out of the trusted click');
expect(local.includes('ensureGameSfxContext()'),'gameplay SFX WebAudio unlock helper missing');
expect(local.includes('ctx.state==="closed"'),'closed WebAudio context recreation missing');
expect(local.includes('ctx.state==="running"'),'running WebAudio state handling missing');
expect(local.includes('const p=ctx.resume()'),'non-running WebAudio resume call missing');
expect(local.includes('unlockSilentFrame(ctx)'),'Safari silent unlock frame missing');
expect(local.includes('window.__sixBallSfxLazyInit=true'),'SFX must be lazily initialized by a real user gesture');
expect(!/Bgm\.init\(\);[\s\S]{0,250}ensureGameSfxContext\(\);[\s\S]{0,100}sync\(\);/.test(local),'SFX AudioContext must not be eagerly initialized at module load');
expect(local.includes('Sfx.__sixBallSafariResumeBridge=true'),'SFX resume bridge marker missing');
expect(local.includes('window.__sixBallSfxSafariResumeBridge=true'),'SFX recovery diagnostic marker missing');
expect(local.includes('a.loop=true'),'BGM must loop');
expect(!local.includes('stepEngine(')&&!local.includes('settlePass(')&&!local.includes('SLIDE_SPEED')&&!local.includes('GRAV='),'local audio adapter must not alter gameplay physics');
console.log('same-origin gameplay BGM + Safari interrupted/closed SFX recovery regression PASS');
